name: "latest"

on:
  push:
    branches:
      - "master"

jobs:
  latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: cd esp-idf && ./install.sh
      - run: source esp-idf/export.sh && make
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "latest build"
          files: |
            build/radiov3.bin
            build/ota_matifest.txt